'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { AlertTriangle, Banknote, Eye, FileBarChart, FileText, Printer, RefreshCw, Search, ShieldAlert, Undo2, X } from 'lucide-react';
import { getParametresDocuments, nomEntrepriseDocument, couleurPrincipaleDocument, type ParametresDocuments } from '../../services/documents.service';

const API = process.env.NEXT_PUBLIC_API_URL || 'https://messiematala-pos-backend-production.up.railway.app';
type TypeRapport = 'Journalier' | 'Hebdomadaire' | 'Mensuel' | 'Annuel' | 'Periode' | 'ParCaissier';
type Onglet = 'rapports' | 'operations';

type Vente = { id_vente:number; codefacture?:string; datevente?:string; nomclient?:string; nomcaissier?:string; modepaiement?:string; devise?:string; montanttotal?:any; statut?:string; typeoperation?:string; total_paye?:any; total_rembourse?:any };

function today(){return new Date().toISOString().slice(0,10)}
function money(v:any,d=''){const n=Number(v||0);return `${n.toLocaleString('fr-FR',{maximumFractionDigits:2})} ${d}`.trim()}
function inputDate(d:Date){return d.toISOString().slice(0,10)}
function periode(type:TypeRapport, base:string){const d=new Date(`${base}T00:00:00`); if(type==='Journalier')return{debut:base,fin:base,disabled:true}; if(type==='Hebdomadaire'){const diff=(d.getDay()+6)%7; const l=new Date(d); l.setDate(d.getDate()-diff); const di=new Date(l); di.setDate(l.getDate()+6); return{debut:inputDate(l),fin:inputDate(di),disabled:true}} if(type==='Mensuel'){return{debut:inputDate(new Date(d.getFullYear(),d.getMonth(),1)),fin:inputDate(new Date(d.getFullYear(),d.getMonth()+1,0)),disabled:true}} if(type==='Annuel'){return{debut:inputDate(new Date(d.getFullYear(),0,1)),fin:inputDate(new Date(d.getFullYear(),11,31)),disabled:true}} return{debut:base,fin:base,disabled:false}}

export default function Page(){
 const router=useRouter();
 const [onglet,setOnglet]=useState<Onglet>('rapports'); const [typeRapport,setTypeRapport]=useState<TypeRapport>('Journalier'); const [dateDebut,setDateDebut]=useState(today()); const [dateFin,setDateFin]=useState(today()); const [recherche,setRecherche]=useState('');
 const [ventes,setVentes]=useState<Vente[]>([]); const [stats,setStats]=useState<any>({}); const [synthese,setSynthese]=useState<any[]>([]); const [selectedId,setSelectedId]=useState<number|null>(null); const [loading,setLoading]=useState(false);
 const [venteAnnulation,setVenteAnnulation]=useState<Vente|null>(null); const [motif,setMotif]=useState(''); const [manager,setManager]=useState(''); const [message,setMessage]=useState(''); const [params,setParams]=useState<ParametresDocuments|null>(null);
 const finDisabled=['Journalier','Hebdomadaire','Mensuel','Annuel'].includes(typeRapport); const selected=useMemo(()=>ventes.find(v=>v.id_vente===selectedId)||null,[ventes,selectedId]);
 useEffect(()=>{charger(); chargerDocs()},[]);
 useEffect(()=>{const p=periode(typeRapport,dateDebut); setDateDebut(p.debut); setDateFin(p.fin)},[typeRapport]);
 async function chargerDocs(){try{setParams(await getParametresDocuments())}catch{}}
 async function lire(res:Response){const t=await res.text(); try{return t?JSON.parse(t):null}catch{return t}}
 function qs(){return new URLSearchParams({typeRapport,dateDebut,dateFin,recherche}).toString()}
 async function charger(){setLoading(true); setMessage(''); try{const res=await fetch(`${API}/ventes-manager?${qs()}`,{cache:'no-store'}); const data=await lire(res); if(!res.ok)throw new Error(typeof data==='string'?data:JSON.stringify(data)); setVentes(data.ventes||[]); setStats(data.stats||{}); setSynthese(data.synthesePaiement||[])}catch(e:any){setMessage(String(e.message||e))}finally{setLoading(false)}}
 async function tester(){const res=await fetch(`${API}/ventes-manager/tester-connexion`,{cache:'no-store'}); const data=await lire(res); alert(data?.message||JSON.stringify(data))}
 function ouvrirPdf(kind:'rapport'|'synthese'){const path=kind==='rapport'?'rapport/pdf':'synthese-paiement/pdf'; window.open(`${API}/ventes-manager/${path}?${qs()}`,'_blank')}
 async function annuler(){if(!venteAnnulation)return; if(motif.trim().length<5){alert('Motif trop court.');return} const res=await fetch(`${API}/ventes-manager/${venteAnnulation.id_vente}/annuler`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({motif,manager})}); const data=await lire(res); if(!res.ok){alert(typeof data==='string'?data:JSON.stringify(data));return} setVenteAnnulation(null); setMotif(''); await charger(); alert(data.message||'Vente annulée')}
 const title=nomEntrepriseDocument(params)||'ZAIRE MODE'; const color=couleurPrincipaleDocument(params)||'#166534';
 return <main className="min-h-screen bg-slate-100 p-4 md:p-8"><div className="mx-auto max-w-7xl space-y-5">
  <section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-bold uppercase tracking-wide" style={{color}}>Manager sécurisé</p><h1 className="text-2xl font-black text-slate-900">Ventes Manager — {title}</h1><p className="text-sm text-slate-500">Rapports, opérations sensibles, paiements, PDF, audit et paramètres documents.</p></div><button onClick={charger} className="rounded-2xl bg-slate-900 px-4 py-3 text-sm font-bold text-white"><RefreshCw className="mr-2 inline" size={16}/>Actualiser</button></div></section>
  {message&&<div className="rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700 ring-1 ring-red-200">{message}</div>}
  <section className="grid gap-3 md:grid-cols-4"><div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><p className="text-xs text-slate-500">Total ventes</p><b>{stats.total_ventes||0}</b></div><div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><p className="text-xs text-slate-500">Validées</p><b>{stats.ventes_validees||0}</b></div><div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><p className="text-xs text-slate-500">Annulées</p><b>{stats.ventes_annulees||0}</b></div><div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><p className="text-xs text-slate-500">Remboursé</p><b>{money(stats.total_remboursements)}</b></div></section>
  <section className="rounded-3xl bg-white p-5 ring-1 ring-slate-200"><div className="mb-4 flex gap-2"><button onClick={()=>setOnglet('rapports')} className={`rounded-xl px-4 py-2 font-bold ${onglet==='rapports'?'bg-green-700 text-white':'bg-slate-100'}`}>Rapports</button><button onClick={()=>setOnglet('operations')} className={`rounded-xl px-4 py-2 font-bold ${onglet==='operations'?'bg-red-800 text-white':'bg-slate-100'}`}>Opérations sensibles</button></div>
   <div className="grid gap-3 md:grid-cols-6"><select value={typeRapport} onChange={e=>setTypeRapport(e.target.value as TypeRapport)} className="rounded-xl border p-3"><option>Journalier</option><option>Hebdomadaire</option><option>Mensuel</option><option>Annuel</option><option>Periode</option><option>ParCaissier</option></select><input type="date" value={dateDebut} onChange={e=>setDateDebut(e.target.value)} className="rounded-xl border p-3"/><input type="date" value={dateFin} disabled={finDisabled} onChange={e=>setDateFin(e.target.value)} className="rounded-xl border p-3 disabled:bg-slate-100"/><input value={recherche} onChange={e=>setRecherche(e.target.value)} placeholder="Recherche facture, client..." className="rounded-xl border p-3 md:col-span-2"/><button onClick={charger} className="rounded-xl bg-green-700 p-3 font-bold text-white"><Search className="mr-2 inline" size={16}/>Rechercher</button></div>
  </section>
  {onglet==='rapports'&&<section className="grid gap-4 lg:grid-cols-3"><div className="rounded-3xl bg-white p-5 ring-1 ring-slate-200 lg:col-span-2"><div className="mb-3 flex flex-wrap gap-2"><button onClick={()=>ouvrirPdf('rapport')} className="rounded-xl bg-blue-700 px-4 py-2 font-bold text-white"><FileText className="mr-2 inline" size={16}/>Exporter PDF</button><button onClick={()=>ouvrirPdf('synthese')} className="rounded-xl bg-emerald-700 px-4 py-2 font-bold text-white"><FileBarChart className="mr-2 inline" size={16}/>Synthèse PDF</button><button onClick={tester} className="rounded-xl bg-slate-700 px-4 py-2 font-bold text-white">Tester connexion</button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-slate-50 text-left"><th className="p-3">ID</th><th>Facture</th><th>Date</th><th>Client</th><th>Total</th><th>Statut</th><th>Action</th></tr></thead><tbody>{ventes.map(v=><tr key={v.id_vente} onClick={()=>setSelectedId(v.id_vente)} className={`cursor-pointer border-t ${selectedId===v.id_vente?'bg-green-50':'hover:bg-slate-50'}`}><td className="p-3">{v.id_vente}</td><td>{v.codefacture}</td><td>{v.datevente?new Date(v.datevente).toLocaleString('fr-FR'):'-'}</td><td>{v.nomclient}</td><td>{money(v.montanttotal,v.devise)}</td><td>{v.statut}</td><td><button onClick={(e)=>{e.stopPropagation();router.push(`/dashboard/ventes/detail?id=${v.id_vente}`)}} className="rounded-lg bg-slate-900 px-3 py-1 text-white"><Eye size={14}/></button></td></tr>)}</tbody></table></div></div><div className="rounded-3xl bg-white p-5 ring-1 ring-slate-200"><h2 className="mb-3 font-black"><Banknote className="mr-2 inline"/>Synthèse paiement</h2>{synthese.map((s,i)=><div key={i} className="mb-2 rounded-xl bg-slate-50 p-3"><b>{s.modepaiement}</b><p>{s.nombre} paiement(s) — {money(s.total,s.devise)}</p></div>)}</div></section>}
  {onglet==='operations'&&<section className="rounded-3xl bg-white p-5 ring-1 ring-slate-200"><h2 className="mb-4 text-xl font-black"><ShieldAlert className="mr-2 inline text-red-700"/>Opérations sensibles</h2><div className="grid gap-3 md:grid-cols-4"><button disabled={!selected} onClick={()=>selected&&router.push(`/dashboard/ventes/detail?id=${selected.id_vente}`)} className="rounded-2xl bg-blue-700 p-4 font-bold text-white disabled:opacity-40"><Eye className="mr-2 inline"/>Ouvrir détails</button><button disabled={!selected} onClick={()=>selected&&setVenteAnnulation(selected)} className="rounded-2xl bg-red-800 p-4 font-bold text-white disabled:opacity-40"><AlertTriangle className="mr-2 inline"/>Annuler vente</button><button disabled={!selected} onClick={()=>selected&&router.push(`/dashboard/annulations?idVente=${selected.id_vente}`)} className="rounded-2xl bg-amber-600 p-4 font-bold text-white disabled:opacity-40"><Undo2 className="mr-2 inline"/>Retour produits</button><button onClick={()=>window.open(`${API}/ventes-manager/resume-encaissements?${qs()}`,'_blank')} className="rounded-2xl bg-emerald-700 p-4 font-bold text-white"><Printer className="mr-2 inline"/>Total jour</button></div>{selected&&<p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm">Vente sélectionnée : <b>#{selected.id_vente}</b> — {selected.codefacture} — {money(selected.montanttotal,selected.devise)}</p>}</section>}
  {venteAnnulation&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-xl"><div className="mb-4 flex justify-between"><h3 className="text-xl font-black text-red-800">Annuler la vente #{venteAnnulation.id_vente}</h3><button onClick={()=>setVenteAnnulation(null)}><X/></button></div><input value={manager} onChange={e=>setManager(e.target.value)} placeholder="Manager validateur" className="mb-3 w-full rounded-xl border p-3"/><textarea value={motif} onChange={e=>setMotif(e.target.value)} placeholder="Motif obligatoire" className="mb-3 h-28 w-full rounded-xl border p-3"/><button onClick={annuler} className="w-full rounded-2xl bg-red-800 p-3 font-black text-white">Confirmer l’annulation</button></div></div>}
 </div></main>
}
